

# my jar of words contains 4 I, 4 am, and 2 Joe
jar <- c(4,4,2)

# my mug of words contains 3 I, 1 am, and 1 Joe
mug <- c(3,1,1)

# if I reach in and draw four words (with replacement) and get the sentence "I I am am",
# what's the probability that document would have been generated by the jar?
document <- c(2,2,0)

# six permutations:
# I I am am
# I am I am
# I am am I
# am am I I
# am I am I
# am I I am

# the probability I draw that vector of words = the number of permutations times the
# probability of each word
6 * 0.4 * 0.4 * 0.4 * 0.4

# this is built in to R with the dmultinom() function
dmultinom(x = document, prob = jar)

# now, what is P(document | mug)?
dmultinom(x = document, prob = mug)

# it's roughly twice as likely to have been generated by the jar as the mug.



## Is this "statistically significant"?
## In other words, is this a likelihood ratio we wouldn't expect to observe by chance?

# Null Hypothesis: It was drawn from the mug. If we draw 10,000 documents from the mug,
# what's the probability we get a likelihood ratio in favor of the jar as large or larger
# than the one we observed?
get_lr <- function(doc){
  dmultinom(x = doc, prob = jar) / dmultinom(x = doc, prob = mug)
}
get_lr(document)

# draw 10,000 documents from the mug using the rmultinom() function
draws <- rmultinom(n = 10000, size = 4, prob = mug)

simulated_likelihood_ratios <- apply(draws, 2, get_lr)

hist(simulated_likelihood_ratios)

# p-value is the probability of getting a likelihood ratio as large or larger
# than the one we observed
sum(simulated_likelihood_ratios > get_lr(document)) / length(simulated_likelihood_ratios)



## we can also look at the cosine similarity scores between these vectors.
## the most similar vectors have the smallest angle between them
# define cosine similarity
cosine_similarity <- function(x1, x2){
  sum(x1*x2) / sqrt(sum(x1^2)) / sqrt(sum(x2^2))
}

cosine_similarity(document, jar)
cosine_similarity(document, mug)

# the document is more similar to the jar vector than the mug vector,
# the same result we got from the multinomial model
